# Generated by Django 2.2.7 on 2019-12-19 15:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='gender',
        ),
        migrations.AddField(
            model_name='organizer',
            name='description',
            field=models.TextField(default='Test Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_dir),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='biography'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Contact number must contain digits only. Up to 10 digits allowed.', regex='^\\d{6,10}$')], verbose_name='contact no'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='last_name'),
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{6,10}$')], verbose_name='primary contact no')),
                ('secondary_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{6,10}$')], verbose_name='secondary contact no')),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', related_query_name='contact', to='users.Organizer')),
            ],
        ),
    ]
