# Generated by Django 3.0.1 on 2020-01-28 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0009_auto_20200120_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', related_query_name='user', to='locations.Location'),
        ),
    ]
