# Generated by Django 3.0.1 on 2020-01-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
