# Generated by Django 2.2.7 on 2019-12-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Organizer',
        ),
    ]
