# Generated by Django 2.2.7 on 2019-12-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191216_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='middle_name',
        ),
    ]
