# Generated by Django 2.2.7 on 2019-12-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_volunteer_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
