# Generated by Django 2.2.7 on 2019-12-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191219_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='last name'),
        ),
    ]
