# Generated by Django 2.2.7 on 2020-01-20 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_auto_20191226_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', related_query_name='event', to='users.Organizer', verbose_name='organizer')),
            ],
            options={
                'ordering': ['-timestamp', '-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='SavedEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_events', related_query_name='saved_event', to='event.Event')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_events', related_query_name='saved_event', to='users.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventtypes', related_query_name='eventtype', to='event.Event')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventtypes', related_query_name='eventtype', to='event.Type')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='types',
            field=models.ManyToManyField(related_name='events', related_query_name='event', through='event.EventType', to='event.Type', verbose_name='categories'),
        ),
    ]
