# Generated by Django 3.0.1 on 2020-01-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200126_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedevent',
            options={'ordering': ['-id']},
        ),
    ]
